### ISSUE TITLE
client.account.balance is not working

### ISSUE THREAD

**Issue by ciocan** [ArkEcosystem/ark-ts#16]
I have tried to get the balance using

```
import { Client, Network, NetworkType } from 'ark-ts';
const net = Network.getDefault(NetworkType.Mainnet);
const client = new Client(net);
const address = 'ATRjRVegVoAtfWbbuUsB35z5ruGBcuPJop'
client.account.publicKey({ address }).subscribe(console.log)
client.account.balance({ address }).subscribe(console.log)
```

and I get undefined

![screenshot 2018-03-12 21 46 16](https://user-images.githubusercontent.com/4984377/37311349-d45cc4f2-263e-11e8-9c64-e2a054ac3e90.png)

**Comment by luciorubeens** [comment]
True that, I'll check. You can use `client.account.get({ address })` instead.
