### ISSUE TITLE
Bug In ts definition of transaction list api

### ISSUE THREAD

**Issue by vekexasia** [ArkEcosystem/ark-ts#6]
Hello, 

`TransactionApi.list` is set to return a `model.TransactionResponse` which is defined as follow:

```typescript
export class TransactionResponse {
  @JsonProperty('success')
  success: boolean;

  @JsonProperty({name: 'transactionIds'})
  transactionIds: string[];

  constructor() {
    this.success = void 0;
    this.transactionIds = void 0;
  }
}
```

But the response of `/api/transactions/list` endpoint from `ark-node` does not return such response but rather something similar to this one

```typescript
export class TransactionListResponse {
  @JsonProperty('success')
  success: boolean;

  @JsonProperty({clazz: Transaction, name: 'transactions'})
  transactions: Transaction[];

  constructor() {
    this.success = void 0;
    this.transactions = void 0;
  }
}
```

I noticed your `TransactionResponse` is used in many places within Transaction.ts code so I guess there are more bugs related to this one.

**Comment by luciorubeens** [comment]
Solved

**Comment by vekexasia** [comment]
Thanks.
